# DeluxeMenus 1.13.1-Release main configuration file
# 
# A full wiki on how to use this plugin can be found at:
# https://github.com/help-chat/DeluxeMenus/wiki

debug: false
check_updates: true
gui_menus:
  solomapgui:
    file: solomapgui.yml
  soloopengui:
    file: soloopengui.yml